# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

before_install:
  cd hello
  make
  cd ../failedTest
  make
script:
  cd hello
  ./hello
  cd ../failedTest
  ./failedTest
